// <auto-generated />
namespace ManagementTool.Roles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FullNameAndSurname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullNameAndSurname));
        
        string IMigrationMetadata.Id
        {
            get { return "201901182114339_FullNameAndSurname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
